### ISSUE TITLE
Missing file: walldodb.configdb

### ISSUE THREAD

**Issue by cr0hn** [zionsSpartans/wall-do-hackathon#4]
El fichero de inicialización de la base de datos no existe, por lo que no se puede probar el proyecto:

<img width="738" alt="wall-do-hackathon_whitelist_py_at_master_ _zionsspartans_wall-do-hackathon" src="https://user-images.githubusercontent.com/4076390/49305075-8238c900-f4ce-11e8-8698-ec81771b40c1.png">

**Comment by andoniaf** [comment]
En las instrucciones de despliegue indicamos donde generarlo:
![imagen](https://user-images.githubusercontent.com/14891798/49308979-152b3080-f4da-11e8-8ce2-ecc3ee3ce3ab.png)

Tenemos pendiente hacer que todas las configuraciones se hagan desde un unico fichero de configuración global para facilitar el despliegue.
